### ISSUE TITLE
상용 소프트웨어 조사

### ISSUE THREAD

**Issue by AnOldStory** [osamhack2021/Web_ArmyForm_LFDF#1]
상용 소프트웨어 조사 및 결과 토의

멘토 님이 추천하신 사이트 -> https://www.typeform.com/

**Comment by AnOldStory** [comment]
# SurveyJs 
- Demo : https://surveyjs.io/Examples/Library
-
수정중

**Comment by tshong3** [comment]
## Form.io
---
- 공식사이트 : https://www.form.io/

- Demo : http://codepen.io/travist/full/xVyMjo/

- 장점 : 드로그 앤 드롭 방식으로 다양한 질문 형태 추가 가능, 이벤트 설정 가능, 셀프 호스팅 가능, 도커화

- 단점 : 디자인 변경이 힘듦, db 스키마의 단순환 result를 모두 JSON으로 나옴

- 라이선스 : MIT

- nodejs + mongodb 서버 데모 https://github.com/formio/formio

**Comment by ironore15** [comment]
# SurveyJs 
- github 링크 https://github.com/simonv3/quick-survey/
- Demo : https://apps.sandstorm.io/app/wupmzqk4872vgsye9t9x5dmrdw17mad97dk21jvcm2ph4jataze0
- 장점 : Meteor 기반 javascript, form 생성 난이도 낮음
- 단점 : 마지막 커밋 3년 전, 적은 질문 타입 (number, text, email, textarea, radio, checkbox, date)
- 라이선스 : MIT

**Comment by ironore15** [comment]
개인적으로 살펴봤을 때는 SurveyJs가 가장 사용하기 편한 것 같아요. 각자 의견 남겨주세요.

**Comment by AnOldStory** [comment]
> 개인적으로 살펴봤을 때는 SurveyJs가 가장 사용하기 편한 것 같아요. 각자 의견 남겨주세요.

수정하기엔 Surveyjs가 좋아보이긴하네요 로그인같은걸 추가시키고 하기 편하네요 나머지분들은 어떻게 생각하시낭 ㅛ

**Comment by AnOldStory** [comment]
오늘 새벽까지 올려둘게요
